### ISSUE TITLE
Downloaded levels have asian text and not available in-game

### ISSUE THREAD

**Issue by jeyjai** [blawar/mmlinx#11]
Hey, i just got mmlinx so I'm not sure what might be causing this but browsing levels in "download" works just fine, and if i download a level it tells me it's successfully installed and which slot it's in.

But... When i switch to "current levels" all my installed levels are just scrambled information. The titles are asian symbols mixed with other symbols, course id is wrong and released date is off. Almost looks like it's encrypted.
And then when i start mario maker 2, none of the installed levels shows up
I'll add a photo of it
![20221120_200555](https://user-images.githubusercontent.com/7854537/202921743-0eb844ec-51ca-4aa3-bbac-46cb81f42e3a.jpg)

**Comment by Tennstrong** [comment]
Also having this issue - seems to overwrite the save data for the game on each write (i.e. story mode progress is wiped)

E: further info, tried saving a level into slot 0 (which it recognized but labeled as gibberish), then in mmlinx saved into slots 1/2, going back into SMM2 it had erased everything including the original level saved within SMM2. Since I'm not on 15.0, I think I'm going to try downgrading my mmlinx version & retrying. Unsure if it's a 3.02 issue [new SMM2 patch] or a 15.0 [mmlinx ver] issue. 

E2: Tried both options - assuming you aren't on 15.0 atmosphere you are fine using the 8.02 version, mmlinx 15.0 still gets the same errors on SMM2 1.0, no issues using MMLinx 8.02 w/ SMM2 3.02

**Comment by naurkleatt** [comment]
Where can I get MMLinx 8.02? I have the same problem and I can't find the older version of MMLinx.

**Comment by jeyjai** [comment]
> Where can I get MMLinx 8.02? I have the same problem and I can't find the older version of MMLinx.

Doesn't matter which mmlinx version you're using, it won't work as long as your switch itself is on firmware 15.0.0 or 15.0.1
I've already tried that, but I'll link it to you if you still want to try it yourself.

The only 2 versions on github is 8.1 from 2020 and 15.0 from 2022, so I'm not sure about 8.02 that you mentioned, but here's the only other version available on github
https://github.com/blawar/mmlinx/releases/tag/v8.1

**Comment by giuseppe1010** [comment]
Has anyone fixed this issue? Mine still isn’t working

**Comment by jeyjai** [comment]
> Has anyone fixed this issue? Mine still isn’t working

Nope and i wouldn't expect it to get fixed any time soon. I just bought the game instead and play it online.

But there are level packs uploaded in save files that let's you restore a save file and get a specific pack of levels or worlds.
This is a link to **silvershadow**'s google drive, full of great packs.
https://drive.google.com/drive/mobile/folders/1T2YlyfIDyhLpCYrQ6kWef2BqzvMaceVn?usp=sharing

It's not updated that often but when it is, he usually posts updates on it in the MM-LINX thread over at gbatemp. Pretty sure they also talk about how to install them
https://gbatemp.net/threads/mm-linx-super-mario-maker-2-level-injector.542389/

**Comment by luca30072021** [comment]
I know the answer is a bit late, but I found a solution (relatively).  

You need to downgrade your system to version 14.1.2 using Daybreak (just saying Darthsternie), after that you install mmlinx version 8.1 and it works again. 

That was the only thing that worked for me and I don't care if my switch is on version 16.x, 15x or anything else.

Maybe this will help people who still have this problem.

**Comment by jeyjai** [comment]
> You need to downgrade your system to version 14.1.2 using Daybreak (just saying Darthsternie), after that you install mmlinx version 8.1 and it works again.

Yea I've already pointed out that it doesn't work on 15 and higher, and if the old version on 14 worked its fairly obvious that downgrading would fix it

**Comment by MYusufY** [comment]
What is the difference between 16, 15, 14? I will try downgrading then.

And I have an question, Does using version 8.1 of mmlinx affect the number of courses? Will it be the same as version 15 or will old courses appear? 

EDIT: We lose all save data, so I can't downgrade.

**Comment by MYusufY** [comment]
Any other solutions there?
